CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('PATIENT', 'DOCTOR', 'ADMIN'))
);

CREATE TABLE patients (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT       NOT NULL,
    full_name        VARCHAR(150) NOT NULL,
    dob              DATE,
    phone            VARCHAR(30),
    national_id_enc  VARCHAR(255),
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_patients_user UNIQUE (user_id),
    CONSTRAINT fk_patients_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE doctors (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT       NOT NULL,
    full_name      VARCHAR(150) NOT NULL,
    specialty      VARCHAR(100) NOT NULL,
    bio            TEXT,
    working_start  TIME         NOT NULL DEFAULT '09:00',
    working_end    TIME         NOT NULL DEFAULT '17:00',
    slot_minutes   INT          NOT NULL DEFAULT 30,
    CONSTRAINT uq_doctors_user UNIQUE (user_id),
    CONSTRAINT fk_doctors_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_doctors_slot CHECK (slot_minutes BETWEEN 5 AND 240),
    CONSTRAINT ck_doctors_hours CHECK (working_start < working_end)
);

CREATE INDEX idx_doctors_specialty ON doctors (lower(specialty));
