CREATE TABLE appointments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id  BIGINT       NOT NULL,
    doctor_id   BIGINT       NOT NULL,
    start_time  TIMESTAMPTZ  NOT NULL,
    end_time    TIMESTAMPTZ  NOT NULL,
    status      VARCHAR(20)  NOT NULL,
    reason      VARCHAR(500),
    version     BIGINT       NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_appt_patient FOREIGN KEY (patient_id) REFERENCES patients (id),
    CONSTRAINT fk_appt_doctor  FOREIGN KEY (doctor_id)  REFERENCES doctors (id),
    CONSTRAINT ck_appt_status  CHECK (status IN ('BOOKED', 'CANCELLED', 'COMPLETED')),
    CONSTRAINT ck_appt_range   CHECK (end_time > start_time)
);

-- A doctor can hold at most one BOOKED appointment per start time; cancelled slots stay rebookable.
CREATE UNIQUE INDEX uq_appt_doctor_active_start ON appointments (doctor_id, start_time) WHERE status = 'BOOKED';
CREATE INDEX idx_appt_doctor_start ON appointments (doctor_id, start_time);
CREATE INDEX idx_appt_patient_start ON appointments (patient_id, start_time);

CREATE TABLE prescriptions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id BIGINT       NOT NULL,
    medication     VARCHAR(200) NOT NULL,
    dosage         VARCHAR(100) NOT NULL,
    instructions   TEXT,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_rx_appt FOREIGN KEY (appointment_id) REFERENCES appointments (id)
);
CREATE INDEX idx_rx_appointment ON prescriptions (appointment_id);

CREATE TABLE audit_logs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT      NOT NULL,
    actor_role    VARCHAR(20) NOT NULL,
    action        VARCHAR(50) NOT NULL,
    resource_type VARCHAR(50) NOT NULL,
    resource_id   BIGINT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_audit_actor ON audit_logs (actor_user_id, created_at);
CREATE INDEX idx_audit_resource ON audit_logs (resource_type, resource_id);
CREATE INDEX idx_audit_created ON audit_logs (created_at);
